//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_WEBNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiThiH
    {
        public string IDBaiThiHS { get; set; }
        public string IDBaiThi { get; set; }
        public Nullable<System.TimeSpan> ThoiGianLamBai { get; set; }
        public string TongSoDiem { get; set; }
        public string IDStudent { get; set; }
    
        public virtual BaiThi BaiThi { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
