//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_WEBNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBTH
    {
        public string IDBaiThiHS { get; set; }
        public string IDCauHoi { get; set; }
        public string CauTraLoi { get; set; }
        public string DapAn { get; set; }
    }
}
